### ISSUE TITLE
Download pre-built Android Swappy Frame Pacing Library

### ISSUE THREAD

**Issue by fire** [V-Sekai/world-godot#50]
```
- name: Download pre-built Android Swappy Frame Pacing Library
  uses: dsaltares/fetch-gh-release-asset@1.1.2
  with:
    repo: darksylinc/godot-swappy
    version: tags/v2023.3.0.0
    file: godot-swappy.7z
    target: swappy/godot-swappy.7z

- name: Extract pre-built Android Swappy Frame Pacing Library
  run: 7za x -y swappy/godot-swappy.7z -o${{github.workspace}}/thirdparty/swappy-frame-pacing
```
